In [9]:
import numpy as np

# Features data
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])

# Target data
y = np.array([[1], [2], [3], [4]])

# Save the features and target data to files
np.savetxt('features.txt', X)
np.savetxt('target.txt', y)


In [10]:
import numpy as np

#linear regression defined as h(x) = y = theta0 + theta1 * x1 
def linear_regression(X, y, learning_rate=0.01, num_epochs=100):
    """
    Train a linear regression model using batch gradient descent
    :param X: Features data
    :param y: Target data
    :param learning_rate: Learning rate for gradient descent
    :param num_epochs: Number of epochs
    :return: Trained model parameters
    """
    m, n = X.shape #number of samples and number of features
    theta = np.zeros((n, 1)) #define theta0 and theta1 as 0
    print("array")
    
    for epoch in range(num_epochs):
        y_pred = X @ theta # compute the predicted values through a matrix multiplication
        error = y - y_pred # compute the error
        gradient = -(2/m) * X.T @ error #derivative of the cost function
        theta = theta - learning_rate * gradient # update the model parameters
        print(theta)

    return theta

# Load the features and target data
X = np.loadtxt('features.txt')
y = np.loadtxt('target.txt').reshape(-1, 1)

# Train the linear regression model using batch gradient descent
theta = linear_regression(X, y)

array
[[0.15]
 [0.2 ]]
[[0.2375]
 [0.316 ]]
[[0.288675]
 [0.38318 ]]
[[0.31873775]
 [0.4219864 ]]
[[0.33652981]
 [0.44430252]]
[[0.34718983]
 [0.45703488]]
[[0.35370438]
 [0.4641975 ]]
[[0.35780922]
 [0.4681233 ]]
[[0.36051318]
 [0.47016816]]
[[0.36240257]
 [0.47112012]]
[[0.36381816]
 [0.47143717]]
[[0.364958 ]
 [0.4713855]]
[[0.3659372 ]
 [0.47111982]]
[[0.36682266]
 [0.47073003]]
[[0.36765325]
 [0.47026839]]
[[0.36845159]
 [0.46976527]]
[[0.3692308 ]
 [0.46923833]]
[[0.36999851]
 [0.46869782]]
[[0.37075917]
 [0.46814971]]
[[0.37151535]
 [0.46759745]]
[[0.37226856]
 [0.46704307]]
[[0.37301966]
 [0.46648773]]
[[0.37376917]
 [0.46593211]]
[[0.37451737]
 [0.46537661]]
[[0.37526444]
 [0.46482145]]
[[0.37601049]
 [0.46426677]]
[[0.37675556]
 [0.46371264]]
[[0.3774997 ]
 [0.46315912]]
[[0.37824292]
 [0.46260622]]
[[0.37898524]
 [0.46205396]]
[[0.37972666]
 [0.46150234]]
[[0.38046719]
 [0.46095138]]
[[0.38120684]
 [0.46040107]]
[[0.3819456 ]
 [0.45985141]]
[[0.38268348]
 [0.45930241]]
[[0.3

In [11]:
print(theta)

[[0.42880309]
 [0.42498801]]


If you want some more details about the gradient implementation take a look at this tutorial: https://towardsdatascience.com/gradient-descent-from-scratch-e8b75fa986cc